import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: "Cocktail Recipes",
    description: "Ανακάλυψε εύκολες και γρήγορες συνταγές για cocktails όπως Mojito, Margarita, Daiquiri και άλλα. Ιδανικό για bartenders & λάτρεις των ποτών!",
    metadataBase: new URL('https://shakermap.vercel.app'),
    keywords: ["cocktails", "συνταγές κοκτέιλ", "mojito", "margarita", "daiquiri", "ρούμι", "λάιμ", "ποτά", "bar", "bartending"],
    robots: "index, follow",
    canonical: "https://shakermap.vercel.app/",
    alternates: {},
    verification: {
      google: 'qZFCnauU7LTRbNyPupI8ZzCluUF4AVpjNiULySKtACQ', // Κωδικός επαλήθευσης της Google
    },
    openGraph: {
      title: "🍹 Cocktail Recipes | Συνταγές για Mojito & άλλα",
      description: "Δες πώς να φτιάξεις Mojito, Margarita και άλλα αγαπημένα cocktails βήμα-βήμα.",
      url: "https://shakermap.vercel.app/",
      images: [
        {
          url: "https://shakermap.vercel.app/cocktails.png",
          width: 1300,
          height: 1024,
          alt: "Cocktail Recipes – Mojito, Margarita και άλλα",
        },
      ],
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
    },
  icons: {
    // icon: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='0.9em' font-size='90'>🍹</text></svg>",
    icon: "/favicon.ico",
    // shortcut: "data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20100%20100'%3E%3Ctext%20y='0.9em'%20font-size='90'%3E%F0%9F%8D%B9%3C/text%3E%3C/svg%3E",
    // apple: "data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20100%20100'%3E%3Ctext%20y='0.9em'%20font-size='90'%3E%F0%9F%8D%B9%3C/text%3E%3C/svg%3E",
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
